title: Cantika # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Undergraduate economics student who interesting to art, movies, and learn new things  
  <br><br>
  <a href="https://www.instagram.com/cantiiika/">Instagram</a>  
  <br><br>
  <a href="https://www.linkedin.com/in/cantikas/">View My LinkedIn Profile</a> 
  
  
  
  
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
